<?php
/*
|--------------------------------------------------------------------------
| Ryu-Installer
|--------------------------------------------------------------------------
|
| This is magic, you can use this file for calling all files required.
| Every product has "signature" and every signature was different.
| Just upload this file to your hosting and access it, simple.
|
*/

// Hello {username} !, Just upload it to your cpanel or hosting.
// after that access it in browser.
// example : https://exampledomain.com/installer-your_name.php
// 
// love u dear.
// This file generated by : RyuJin Framework at {date}



Class RyuMagician{
    private $SIGNATURE_KEY = "{signature_key}";
    private $API_URL       = "https://dash.shinryujin.net/api/v1/install";
    
    private $UNZIP = 'https://dash.shinryujin.net/repo/unzip.php.txt';
   //private $UNZIP ='https://gist.githubusercontent.com/ryujinsoft/4878ccd1667af6783b78085a6efd13b9/raw/625e5e50f92145c45151e419162c5df8a7bfba78/unzip.php';

    private $FILE = 'ryujin_{product}.zip';
    private $TYPE = '{product}';

   
    public function install()
    {
        $ver = (float)phpversion();
        echo '<html><head><title>RyuJin App Installing Application ...</title></head><body><center>';
        if(!function_exists('curl_init')){
        echo '<h1>RyuJin App</h1><small><font color=red>PHP-CURL NOT INSTALLED,PLEASE INSTALL AND TRY AGAIN.</font></small></center></body></html>';
        exit;
        }elseif($ver < '7.1'){
            echo '<h1>RyuJin App</h1><small><font color=red>PHP VERSION NOT SUPPORTED MUST BE php7.1 or higher. YOUR CURRENT PHP VERSION IS '.$ver.'</font></small></center></body></html>';
            exit;
        }else{
            echo '<h1>RyuJin App</h1>';
            echo '<b>You are installing <i>'.$this->TYPE.'</></b><br>';
            echo '<div id="alert"></div>';
            echo '<img src="https://c.tenor.com/I6kN-6X7nhAAAAAj/loading-buffering.gif" id="loading">';
        
        echo '<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>';
        echo '<script type="text/javascript">
        $(document).ready(function(){
            $("#loading").hide();
           var req= $.ajax({
                url : "?run=true",
                method: "GET",
                beforeSend:function()
                {
                    $("#loading").show();
                    $("#alert").html("<font color=orange>Installing application please wait...</font>");
                },success:function(data)
                {
                    $("#alert").html(data);
                    $("#loading").hide();
                }
            });
        });
     
        </script>';
    }
    }
    public function parse($x)
    {
        return json_decode($x, true);
    }
    public function getDomain()
    {
        $domain= preg_replace('/www\./i', '', $_SERVER['SERVER_NAME']);
        $domain = ($domain == '127.0.0.1') ? "localhost" : $domain;
        return $domain;
    }
    public function get($fulluris)
    {
        $setup = [
            CURLOPT_URL => $fulluris, 
            CURLOPT_USERAGENT => '@RyuJin-Framework', 
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT=>0,
            CURLOPT_SSL_VERIFYPEER=>false,
            CURLOPT_SSL_VERIFYHOST=>false
        ];
        $c = curl_init();
        curl_setopt_array($c, $setup);
        $e = curl_exec($c);
        return $e;
        curl_close();
    }
   
    public function downloader($source,$filename)
    {
        
        $file = fopen($filename,"w");
        $setup = [
        CURLOPT_URL => $source,
        CURLOPT_FAILONERROR=>true,
        CURLOPT_HEADER=>0,
        CURLOPT_FOLLOWLOCATION=>true,
        CURLOPT_AUTOREFERER=>true,
        CURLOPT_BINARYTRANSFER=>true,
        CURLOPT_TIMEOUT=>0,
        CURLOPT_SSL_VERIFYHOST=>0,
        CURLOPT_SSL_VERIFYPEER=>0,
        CURLOPT_FILE=>$file
        ];
        $c = curl_init();
        curl_setopt_array($c,$setup);
        $e = curl_exec($c);
        return $e;
        curl_close();
    }
    public function getRepo()
    {
        $e = $this->get($this->API_URL.'?signature='.$this->SIGNATURE_KEY .'&pid='.$this->TYPE);
        $data = $this->parse($e);
     
       if($data['code'] == 200 ){
           
           $dl = $this->downloader($data['data']['filename'],$this->FILE);
           if(file_exists($this->FILE) && filesize($this->FILE) > 0)
           {
               if(!$this->unzipper())
               {
                   echo "<b><font color=red>Can't unzip file, please unzip manually or refresh the page.</font></b>";
                   return false;
               }
           }else{
               echo "<b><font color=red>Can't download file, please refresh page.</font></b>";
               return false;
           }
       }else{
           echo '<b><font color=red>Signature key not valid, please download installer from ryu-dashboard again.</font></b>';
           return false;
       }

       return true;
    }
    public function unzipper()
    {
        $this->downloader($this->UNZIP, 'pclzip.lib.php');
        if (@file_exists('pclzip.lib.php'))
        {
            @require 'pclzip.lib.php';
            @$archive = new PclZip($this->FILE);
            if ($archive->extract(PCLZIP_OPT_PATH, __DIR__) == 0)
            {
                return false;
            }
            else
            {
                @unlink('pclzip.lib.php');
                return true;
            }
        }
        else
        {
            return false;
        }
    }
    public function cleaning()
    {
        $this->get($this->API_URL.'?signature='.$this->SIGNATURE_KEY .'&pid='.$this->TYPE.'&d=true');

        if(file_exists('htaccess.txt'))
        {
        $content = file_get_contents('htaccess.txt');
        $content = str_replace("{domain}", $this->getDomain(), $content);
        @file_put_contents('htaccess.txt',$content);
        @rename('htaccess.txt','.htaccess');
        }else{
            $content = "
Options All -Indexes\n
RewriteEngine on\n
RewriteCond %{HTTP_HOST} ^".$this->getDomain()."\$ [NC,OR]\n
RewriteCond %{HTTP_HOST} ^".$this->getDomain()."\$\n
RewriteCond %{REQUEST_URI} !public/\n
RewriteRule (.*) /public/\$1 [L]\n
";
        @unlink('.htaccess');
        @file_put_contents('.htaccess',$content);
        }
        @file_put_contents('app/config/.signature',$this->SIGNATURE_KEY);
        @unlink($this->FILE);
        @unlink('index.php');
        @unlink(__FILE__);
        @unlink(__DIR__.'/hifw');
        
        
    }
    public function runBoy()
    {
        
       if($this->getRepo())
       {
           echo "<b><font color=green> Successfully installed.</font></b>";
           $this->cleaning();
           echo "<meta http-equiv='refresh' content='5;url=/'>";
       }
    }
}


$new = new RyuMagician;
if(isset($_GET['run']))
{
    $new->runBoy();
    exit;
}else{
    $new->install();
}